# Generated by Django 4.0.5 on 2022-06-21 12:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('TIGRAY', 'TIGRAY'), ('AFAR', 'AFAR'), ('AMHARA', 'AMHARA'), ('OROMIA', 'OROMIA'), ('SOMALI', 'SOMALI'), ('BENISHANGUL GUMUZ', 'BENISHANGUL GUMUZ'), ('SNNPR', 'SNNOR'), ('GAMBELLA', 'GAMBELLA'), ('HARARI', 'HARARI'), ('SIDAMA', 'SIDAMA'), ('ADDIS ABABA', 'ADDIS ABABA'), ('DIRE DAWA', 'DIRE DAWA')], max_length=30)),
                ('city', models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Adama', 'Adama'), ('Ambo', 'Ambo'), ('Mekele', 'Mekele'), ('Bahir Dar', 'Bahir Dar'), ('Dire Dawa', 'Dire Dawa'), ('Jimma', 'Jimma'), ('Jijiga', 'Jijiga'), ('Shashamane', 'Shashamane'), ('Bishoftu', 'Bishoftu'), ('Arba Minch', 'Arba Minch'), ('Hawassa', 'Hawassa'), ('Nekemte', 'Nekemte'), ('Gonder', 'Gonder')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('APPLICANT', 'APPLICANT'), ('EMPLOYEE', 'EMPLOYEE')], default='APPLICANT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('ELEMENTARY', 'Elementray school'), ('HIGH_SCHOOL', 'High school'), ('BSc', 'Bachelors degree'), ('MSc', 'Masters degree'), ('PHD', 'Doctorate(PHD)')], max_length=15)),
                ('resume', models.FileField(blank=True, null=True, upload_to='./cv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
