# Generated by Django 4.0.5 on 2022-06-14 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
                ('phone', models.CharField(max_length=13)),
                ('region', models.CharField(choices=[('TIGRAY', 'TIGRAY'), ('AFAR', 'AFAR'), ('AMHARA', 'AMHARA'), ('OROMIA', 'OROMIA'), ('SOMALIYA', 'SOMALIYA')], max_length=30)),
                ('city', models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Adama', 'Adama'), ('Ambo', 'Ambo')], max_length=15)),
                ('education_level', models.CharField(choices=[('ELEMENTARY', 'Elementray school'), ('HIGH_SCHOOL', 'High school'), ('BSc', 'Bachelors degree'), ('MSc', 'Masters degree'), ('PHD', 'Doctorate(PHD)')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='./cv')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('region', models.CharField(choices=[('TIGRAY', 'TIGRAY'), ('AFAR', 'AFAR'), ('AMHARA', 'AMHARA'), ('OROMIA', 'OROMIA'), ('SOMALIYA', 'SOMALIYA')], max_length=30)),
                ('city', models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Adama', 'Adama'), ('Ambo', 'Ambo')], max_length=15)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Architecture', 'Architecture'), ('Construction', 'Construction'), ('Electrician', 'Electrician'), ('Civil Engineer', 'Civil Engineer'), ('Reporter', 'Reporter'), ('Graphic Designer', 'Graphic Designer'), ('Editor', 'Editor'), ('Human Resources Manager', 'Human Resources Manager'), ('Teacher', 'Teacher'), ('Librarian', 'Librarian'), ('Legislator', 'Legislator'), ('Computer Programmer', 'Computer Programmer'), ('Web Developer', 'Web Developer')], max_length=40)),
                ('requirement', models.TextField(help_text='requirements for job')),
                ('education_level', models.CharField(choices=[('ELEMENTARY', 'Elementray school'), ('HIGH_SCHOOL', 'High school'), ('BSc', 'Bachelors degree'), ('MSc', 'Masters degree'), ('PHD', 'Doctorate(PHD)')], max_length=15)),
                ('experience', models.TextField(help_text='required experience for job')),
                ('experience_year', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('FULL_TIME', 'FULL TIME'), ('PART_TIME', 'PART_TIME'), ('REMOTE', 'REMOTE'), ('FREELANCE', 'FREELANCE')], max_length=15)),
                ('region', models.CharField(choices=[('TIGRAY', 'TIGRAY'), ('AFAR', 'AFAR'), ('AMHARA', 'AMHARA'), ('OROMIA', 'OROMIA'), ('SOMALIYA', 'SOMALIYA')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='./cv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobsearch.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.applicant')),
            ],
        ),
    ]
